### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

### ISSUE THREAD

**Issue by modir** [ernw/knxmap#26]
Another problem with neer python versions:

```
$ sudo knxmap  monitor 192.168.1.36 --group-monitor
Traceback (most recent call last):
  File "/usr/local/bin/knxmap", line 33, in <module>
    sys.exit(load_entry_point('KNXmap==0.10.0', 'console_scripts', 'knxmap')())
  File "/usr/local/lib/python3.10/site-packages/KNXmap-0.10.0-py3.10.egg/knxmap/main.py", line 188, in main
  File "/usr/local/lib/python3.10/site-packages/KNXmap-0.10.0-py3.10.egg/knxmap/core.py", line 51, in __init__
  File "/usr/lib64/python3.10/asyncio/queues.py", line 33, in __init__
    super().__init__(loop=loop)
  File "/usr/lib64/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary
```

**Comment by modir** [comment]
Here is the pull request for it: https://github.com/takeshixx/knxmap/pull/27
