### ISSUE TITLE
Brute crash?

### ISSUE THREAD

**Issue by jslawek** [ernw/knxmap#5]
```
root@kali:~/knxmap# python3.5 knxmap.py brute 10.0.0.1 1.1.3
Task exception was never retrieved
future: <Task finished coro=<KnxMap.bruteforce_auth_key() done, defined at /root/knxmap/libknxmap/core.py:70> exception=TypeError("argument of type 'KnxTargets' is not iterable",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/root/knxmap/libknxmap/core.py", line 82, in bruteforce_auth_key
    alive = yield from protocol.tpci_connect(target)
  File "/root/knxmap/libknxmap/bus/tunnel.py", line 291, in tpci_connect
    tunnel_request = self.make_tunnel_request(target)
  File "/root/knxmap/libknxmap/bus/tunnel.py", line 319, in make_tunnel_request
    knx_destination=knx_dst)
  File "/root/knxmap/libknxmap/messages.py", line 1008, in __init__
    self.set_knx_destination(knx_destination)
  File "/root/knxmap/libknxmap/messages.py", line 206, in set_knx_destination
    if '.' in address:
TypeError: argument of type 'KnxTargets' is not iterable

```

**Comment by takeshixx** [comment]
Thanks for the bug report. I've fixed the error and added a new parameter to slightly control the brute forcing key space in the **develop** branch (8e75c080e97c7a6564f1b4a1db7594601e1ea598). Can you please verify if this fixes the issue?

**Comment by jslawek** [comment]
It works, thanks! The Deepsec audience was pleased.

![knxbrute](https://cloud.githubusercontent.com/assets/10602939/20181150/52d2fe76-a75d-11e6-90ca-44d501154966.jpg)

**Comment by takeshixx** [comment]
Amazing, thanks for the picture and greets to everyone in vienna! I hope that exception didn't annoy the participants too much :D
